### ISSUE TITLE
installed `orange3-audio-ijs` from `git` and don't see it, can you help?

### ISSUE THREAD

**Issue by sildeag** [BuDnA/Audio-IJS#3]
An ImportError occurred while loading entry point 'Audio - IJS = orangecontrib.audio.widgets'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Orange/canvas/registry/discovery.py", line 89, in run
    point = entry_point.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'orangecontrib.audio'

**Comment by sildeag** [comment]
Followed your instructions exactly `sudo python3 setup.py develop` and new section added to Orange canvas   X `Audio - IJS`.  Thank you.
